DROP DATABASE hometown;
CREATE DATABASE hometown;

USE hometown;

CREATE TABLE MST_GROUP(
	CODE CHAR(5) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CODE)
);

CREATE TABLE MST_CARD_STEP(
    STEP CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    PRIMARY KEY (STEP)
);

CREATE TABLE MST_CARD(
    CODE CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    HREF varchar(200) NOT NULL,
    STEP CHAR(4) NOT NULL,
    IMG BLOB,
    ICON VARCHAR(50),
    COLOR VARCHAR(50),
    PRIMARY KEY (CODE),
    FOREIGN KEY (STEP) REFERENCES MST_CARD_STEP (STEP)
);

CREATE TABLE MAP_CARD_GROUP(
    GROUP_CODE CHAR(5) NOT NULL,
    CARD_CODE CHAR(4) NOT NULL,
    
    PRIMARY KEY (GROUP_CODE,CARD_CODE),
    FOREIGN KEY (GROUP_CODE) REFERENCES MST_GROUP (CODE),
    FOREIGN KEY (CARD_CODE) REFERENCES MST_CARD (CODE)
);

CREATE TABLE TSN_STATE(
    IDX int NOT NULL AUTO_INCREMENT,
    CREATER VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_UPDATER VARCHAR(255) NULL,
    LAST_UPDATE DATETIME NULL,
    IS_DELETE BOOLEAN DEFAULT FALSE,
    STATE INT NULL,
    
    PRIMARY KEY (IDX)
);


CREATE TABLE TSN_USER (
	ID VARCHAR(255) NOT NULL,
	GIVEN_NAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NULL,
	IMG VARCHAR(255) NULL,
    BACKGROUND_IMG VARCHAR(255) NULL,
	GROUP_CODE CHAR(5) NOT NULL,
    STATE INT NOT NULL,

	PRIMARY KEY(ID),
	FOREIGN KEY (GROUP_CODE) REFERENCES MST_GROUP (CODE),-- ON DELETE CASCADE ON UPDATE RESTRICT
    FOREIGN KEY (STATE) REFERENCES TSN_STATE(IDX) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TSN_COOKIE(
    ID VARCHAR(255) NOT NULL,
    COOKIEKEY VARCHAR(255) NOT NULL,
    IPADDRESS VARCHAR(100),
    LAST_CONNECT_DATE DATE,
    STATE int,
    
    PRIMARY KEY (ID, COOKIEKEY),
    FOREIGN KEY (ID) REFERENCES TSN_USER (ID),-- ON DELETE CASCADE ON UPDATE RESTRICT
    FOREIGN KEY (STATE) REFERENCES TSN_STATE(IDX) ON DELETE CASCADE ON UPDATE RESTRICT
);