DROP DATABASE portal;
CREATE DATABASE portal;
-- ON DELETE CASCADE ON UPDATE RESTRICT
USE portal;

CREATE TABLE MST_GROUP(
	CODE CHAR(5) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CODE)
);

CREATE TABLE MST_CARD_STEP(
    STEP CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    
    PRIMARY KEY (STEP)
);

CREATE TABLE MST_CARD_TYPE(
	CARD_TYPE CHAR(3) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CARD_TYPE)
);

CREATE TABLE MST_CARD_GROUP(
	CARD_GROUP CHAR(4) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ORDER_SEQ INT,
	
	PRIMARY KEY (CARD_GROUP)
);

CREATE TABLE MST_CARD(
    CODE CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    HREF varchar(200) NOT NULL,
    STEP CHAR(4) NOT NULL,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    IMG BLOB,
    ICON VARCHAR(50),
    COLOR VARCHAR(50),
    CARD_TYPE CHAR(3),
    CARD_GROUP CHAR(4),
    ORDER_SEQ INT,
    
    PRIMARY KEY (CODE),
    FOREIGN KEY (STEP) REFERENCES MST_CARD_STEP (STEP),
    FOREIGN KEY (CARD_TYPE) REFERENCES MST_CARD_TYPE (CARD_TYPE),
    FOREIGN KEY (CARD_GROUP) REFERENCES MST_CARD_GROUP (CARD_GROUP)
);

CREATE TABLE MST_STATE(
	STATE INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(STATE)
);

CREATE TABLE MAP_CARD_GROUP(
    GROUP_CODE CHAR(5) NOT NULL,
    CARD_CODE CHAR(4) NOT NULL,
    
    PRIMARY KEY (GROUP_CODE,CARD_CODE),
    FOREIGN KEY (GROUP_CODE) REFERENCES MST_GROUP (CODE),
    FOREIGN KEY (CARD_CODE) REFERENCES MST_CARD (CODE)
);

CREATE TABLE TSN_STATE_INFO(
    IDX INT NOT NULL AUTO_INCREMENT,
    CREATER VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_UPDATER VARCHAR(255) NULL,
    LAST_UPDATE DATETIME NULL,
    IS_DELETE BOOLEAN DEFAULT FALSE,
    STATE INT NULL,
    
    PRIMARY KEY (IDX),
    FOREIGN KEY (STATE) REFERENCES MST_STATE (STATE)
);


CREATE TABLE TSN_USER (
	ID VARCHAR(255) NOT NULL,
	GIVEN_NAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NULL,
	IMG_URL VARCHAR(255) NULL,
	IMG_BLOB BLOB,
    BACKGROUND_IMG VARCHAR(255) NULL,
	GROUP_CODE CHAR(5) NOT NULL,
    STATE INT NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (GROUP_CODE) REFERENCES MST_GROUP (CODE),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX) 
);

CREATE TABLE TSN_PASSWORD(
    IDX INT NOT NULL AUTO_INCREMENT,
    ID VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATE INT NOT NULL,

    PRIMARY KEY (IDX,ID),
    FOREIGN KEY (ID) REFERENCES TSN_USER(ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_COOKIE(
    ID VARCHAR(255) NOT NULL,
    COOKIEKEY VARCHAR(255) NOT NULL,
    IPADDRESS VARCHAR(100) NULL,
    LAST_CONNECT_DATE DATETIME NULL,
    STATE INT NOT NULL,
    
    PRIMARY KEY (ID, COOKIEKEY),
    FOREIGN KEY (ID) REFERENCES TSN_USER (ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_COMMENT(
	IDX INT NOT NULL AUTO_INCREMENT,
	COMMENT TEXT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (IDX),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_APPLICATION(
	IDX INT NOT NULL AUTO_INCREMENT,
	ID VARCHAR(255) NOT NULL,
	COMMENT_IDX INT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (IDX,ID),
	FOREIGN KEY (ID) REFERENCES TSN_USER (ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX),
	FOREIGN KEY (COMMENT_IDX) REFERENCES TSN_COMMENT (IDX)
);








