DROP DATABASE portal;
CREATE DATABASE portal;
-- ON DELETE CASCADE ON UPDATE RESTRICT
USE portal;


CREATE TABLE MST_CARD_STEP(
    STEP CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    
    PRIMARY KEY (STEP)
);

CREATE TABLE MST_CARD_TYPE(
	CARD_TYPE CHAR(3) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (CARD_TYPE)
);

CREATE TABLE MST_ROLE(
	ROLE CHAR(4) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (ROLE)
);

CREATE TABLE MST_CARD(
    CODE CHAR(4) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    HREF varchar(200) NOT NULL,
    STEP CHAR(4) NOT NULL,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    IMG BLOB,
    ICON VARCHAR(50),
    COLOR VARCHAR(50),
    CARD_TYPE CHAR(3),
    ORDER_SEQ INT,
    
    PRIMARY KEY (CODE),
    FOREIGN KEY (STEP) REFERENCES MST_CARD_STEP (STEP),
    FOREIGN KEY (CARD_TYPE) REFERENCES MST_CARD_TYPE (CARD_TYPE)
);

CREATE TABLE MST_STATE(
	STATE INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(STATE)
);

CREATE TABLE TSN_STATE_INFO(
    IDX INT NOT NULL AUTO_INCREMENT,
    CREATER VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME NOT NULL,
    LAST_UPDATER VARCHAR(255) NULL,
    LAST_UPDATE DATETIME NULL,
    IS_DELETE BOOLEAN DEFAULT FALSE,
    STATE INT NULL,
    
    PRIMARY KEY (IDX),
    FOREIGN KEY (STATE) REFERENCES MST_STATE (STATE)
);

CREATE TABLE TSN_COMPANY(
	ID  INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX) 
);

CREATE TABLE TSN_GROUP(
	ID  INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX),
   	FOREIGN KEY (COMPANY_ID) REFERENCES TSN_COMPANY (ID)
);

CREATE TABLE TSN_USER (
	ID VARCHAR(255) NOT NULL,
	GIVEN_NAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NULL,
	IMG_URL VARCHAR(255) NULL,
	IMG_BLOB BLOB,
    BACKGROUND_IMG VARCHAR(255) NULL,
    COMPANY_ID INT NOT NULL,
	GROUP_ID INT NOT NULL,
    STATE INT NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (COMPANY_ID) REFERENCES TSN_COMPANY (ID),
	FOREIGN KEY (GROUP_ID) REFERENCES TSN_GROUP (ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX) 
);

CREATE TABLE TSN_PASSWORD(
    IDX INT NOT NULL AUTO_INCREMENT,
    ID VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATE INT NOT NULL,

    PRIMARY KEY (IDX,ID),
    FOREIGN KEY (ID) REFERENCES TSN_USER(ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_COOKIE(
    ID VARCHAR(255) NOT NULL,
    COOKIEKEY VARCHAR(255) NOT NULL,
    IPADDRESS VARCHAR(100) NULL,
    LAST_CONNECT_DATE DATETIME NULL,
    STATE INT NOT NULL,
    
    PRIMARY KEY (ID, COOKIEKEY),
    FOREIGN KEY (ID) REFERENCES TSN_USER (ID),
    FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_COMMENT(
	IDX INT NOT NULL AUTO_INCREMENT,
	COMMENT TEXT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (IDX),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE TSN_APPLICATION(
	IDX INT NOT NULL AUTO_INCREMENT,
	ID VARCHAR(255) NOT NULL,
	COMMENT_IDX INT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (IDX,ID),
	FOREIGN KEY (ID) REFERENCES TSN_USER (ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX),
	FOREIGN KEY (COMMENT_IDX) REFERENCES TSN_COMMENT (IDX)
);

CREATE TABLE MAP_VIEW_ROLE_COMPANY(
	CARD_CODE CHAR(4) NOT NULL,
	COMPANY_ID INT NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (CARD_CODE,COMPANY_ID),
	FOREIGN KEY (CARD_CODE) REFERENCES MST_CARD(CODE),
	FOREIGN KEY (COMPANY_ID) REFERENCES TSN_COMPANY(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE MAP_VIEW_ROLE_GROUP(
	CARD_CODE CHAR(4) NOT NULL,
	GROUP_ID INT NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (CARD_CODE,GROUP_ID),
	FOREIGN KEY (CARD_CODE) REFERENCES MST_CARD(CODE),
	FOREIGN KEY (GROUP_ID) REFERENCES TSN_GROUP(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);


CREATE TABLE MAP_VIEW_ROLE_USER(
	CARD_CODE CHAR(4) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (CARD_CODE,USER_ID),
	FOREIGN KEY (CARD_CODE) REFERENCES MST_CARD(CODE),
	FOREIGN KEY (USER_ID) REFERENCES TSN_USER(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE MAP_ACTION_ROLE_COMPANY(
	ROLE_CODE CHAR(4) NOT NULL,
	COMPANY_ID INT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (ROLE_CODE,COMPANY_ID),
	FOREIGN KEY (ROLE_CODE) REFERENCES MST_ROLE(ROLE),
	FOREIGN KEY (COMPANY_ID) REFERENCES TSN_COMPANY(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);

CREATE TABLE MAP_ACTION_ROLE_GROUP(
	ROLE_CODE CHAR(4) NOT NULL,
	GROUP_ID INT NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (ROLE_CODE,GROUP_ID),
	FOREIGN KEY (ROLE_CODE) REFERENCES MST_ROLE(ROLE),
	FOREIGN KEY (GROUP_ID) REFERENCES TSN_GROUP(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);


CREATE TABLE MAP_ACTION_ROLE_USER(
	ROLE_CODE CHAR(4) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	STATE INT NOT NULL,
	
	PRIMARY KEY (ROLE_CODE,USER_ID),
	FOREIGN KEY (ROLE_CODE) REFERENCES MST_ROLE(ROLE),
	FOREIGN KEY (USER_ID) REFERENCES TSN_USER(ID),
	FOREIGN KEY (STATE) REFERENCES TSN_STATE_INFO (IDX)
);


