INSERT INTO MST_STATE(STATE,NAME) VALUES('100','Goolgle ID');
INSERT INTO MST_STATE(STATE,NAME) VALUES('101','Private ID');
INSERT INTO MST_STATE(STATE,NAME) VALUES('200','Applying');
INSERT INTO MST_STATE(STATE,NAME) VALUES('201','Application refused');
INSERT INTO MST_STATE(STATE,NAME) VALUES('202','Application approved');
INSERT INTO MST_STATE(STATE,NAME) VALUES('999','Default Transaction Data');

INSERT INTO MST_CARD_STEP(STEP,NAME) VALUES ('HOME','Main tile');
INSERT INTO MST_CARD_STEP(STEP, NAME) VALUES ('ADMN', 'Admin tile');

INSERT INTO MST_CARD_TYPE(CARD_TYPE,NAME) VALUES('IMG','Image Card');
INSERT INTO MST_CARD_TYPE(CARD_TYPE,NAME) VALUES('EVT','Default Card');

INSERT INTO MST_CARD (CODE,NAME,HREF,STEP,TITLE,DESCRIPTION,IMG,ICON,COLOR,CARD_TYPE,ORDER_SEQ) VALUES('ADMN','Admin card','./#!/admin','HOME',null,'Admin',LOAD_FILE('/home/sy/git/Public_Portal_System/PPS.Portal/WebContent/contents/admin.jpg'),null,null,'IMG',1);
INSERT INTO MST_CARD (CODE,NAME,HREF,STEP,TITLE,DESCRIPTION,IMG,ICON,COLOR,CARD_TYPE,ORDER_SEQ) VALUES('APPL','Application card','./#!/application','HOME',null,'Application',LOAD_FILE('/home/sy/git/Public_Portal_System/PPS.Portal/WebContent/contents/application.jpg'),null,null,'IMG',1);
--INSERT INTO MST_CARD (CODE,NAME,HREF,STEP,TITLE,DESCRIPTION,IMG,ICON,COLOR,CARD_TYPE,CARD_GROUP,ORDER_SEQ) VALUES('USAM','User Application management','./#!/applymanagement','ADMN',null,'Application User Management',null,null,null,'IMG','MNGM',1);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO TSN_COMPANY(NAME,STATE) VALUES('Administrator Company',1);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO TSN_GROUP(NAME,COMPANY_ID,STATE) VALUES('Administrator',1,2);
INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO TSN_GROUP(NAME,COMPANY_ID,STATE) VALUES('Guest',1,3);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO TSN_USER (ID,GIVEN_NAME,NAME,NICK_NAME,COMPANY_ID,GROUP_ID,STATE) VALUES('admin','Administrator','Administrator','Administrator',1,1,4);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,null);
INSERT INTO TSN_PASSWORD (ID,PASSWORD,STATE) VALUES('admin',MD5('admin'),5);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO MAP_VIEW_ROLE_COMPANY(CARD_CODE,COMPANY_ID,STATE) VALUES('ADMN',1,6);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO MAP_VIEW_ROLE_GROUP(CARD_CODE,GROUP_ID,STATE) VALUES('ADMN',1,7);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO MAP_VIEW_ROLE_COMPANY(CARD_CODE,COMPANY_ID,STATE) VALUES('APPL',1,8);

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('INIT',now(),false,999);
INSERT INTO MAP_VIEW_ROLE_GROUP(CARD_CODE,GROUP_ID,STATE) VALUES('APPL',2,9);

