INSERT INTO MST_GROUP(CODE,NAME) VALUES('ADMIN','Administrator');
INSERT INTO MST_GROUP(CODE,NAME) VALUES('GUEST','Guest');

INSERT INTO MST_STATE(STATE,NAME) VALUES('100','Goolgle ID');
INSERT INTO MST_STATE(STATE,NAME) VALUES('101','Private ID');

INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('ADMIN',now(),false,101);
INSERT INTO TSN_STATE_INFO (CREATER,CREATE_DATE,IS_DELETE,STATE) values('ADMIN',now(),false,null);
INSERT INTO TSN_USER (ID,GIVEN_NAME,NAME,NICK_NAME,GROUP_CODE,STATE) VALUES('admin','Administrator','Administrator','Administrator','ADMIN',1);
INSERT INTO TSN_PASSWORD (ID,PASSWORD,STATE) VALUES('admin',MD5('admin'),2);

